version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "product-lamda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hsae18665w7i"
s3_prefix = "product-lamda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
